server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:aprLaEsperanzaClaveSuperSecretaTokenJWT2026!}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-server-validation: true
    urls:
      - name: Auth-Service
        url: /api-docs-proxy/Auth-Service
      - name: Socio-Service
        url: /api-docs-proxy/Socio-Service
      - name: Facturacion-Service
        url: /api-docs-proxy/Facturacion-Service
      - name: Pago-Service
        url: /api-docs-proxy/Pago-Service
      - name: Morosidad-Service
        url: /api-docs-proxy/Morosidad-Service
      - name: Incidencia-Service
        url: /api-docs-proxy/Incidencia-Service
      - name: Reparacion-Service
        url: /api-docs-proxy/Reparacion-Service

service:
  auth:
    url: ${SERVICE_AUTH_URL:http://localhost:8081}
  socio:
    url: ${SERVICE_SOCIO_URL:http://localhost:8082}
  facturacion:
    url: ${SERVICE_FACTURACION_URL:http://localhost:8083}
  pago:
    url: ${SERVICE_PAGO_URL:http://localhost:8084}
  morosidad:
    url: ${SERVICE_MOROSIDAD_URL:http://localhost:8085}
  reporte:
    url: ${SERVICE_REPORTE_URL:http://localhost:8086}
  operacion:
    url: ${SERVICE_OPERACION_URL:http://localhost:8087}
  balance:
    url: ${SERVICE_BALANCE_URL:http://localhost:8088}
  incidencia:
    url: ${SERVICE_INCIDENCIA_URL:http://localhost:8089}
  reparacion:
    url: ${SERVICE_REPARACION_URL:http://localhost:8090}